server:
  port: 8081

spring:
  application:
    name: movie-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/movie_db}
    username: ${SPRING_DATASOURCE_USERNAME:msuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mspass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

recommendation:
  service:
    url: ${RECOMMENDATION_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,metrics
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      recommendationService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10                       # last 10 calls considered
        minimum-number-of-calls: 5                    # need >=5 before CB can open
        failure-rate-threshold: 50                    # 50% failures -> OPEN
        wait-duration-in-open-state: 10s              # stays OPEN for 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true

logging:
  level:
    io.github.resilience4j: INFO
    com.cornel.movie: INFO
